networks:
  filemanager:
    name: filemanager

services:
  nginx:
    container_name: filemanager_nginx
    image: nginx:latest
    ports:
      - 8095:80
    volumes:
      - ./www:/var/www
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
    networks:
      - filemanager
    depends_on:
      - php
  php:
    container_name: php_8_3
    build: ./images/php83fpm
    volumes:
      - ./www:/var/www/
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - filemanager
